name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - ruby_version: 3.2
            node_major: 18
            node_version: 18.18.2
            variant: alpine
            tag: alpine
            dockerfile: ./alpine/node18/Dockerfile
          - ruby_version: 3.2
            node_major: 18
            node_version: 18.18.2
            variant: bookworm
            default: true
            dockerfile: ./bookworm/node18/Dockerfile
          - ruby_version: 3.2
            node_version: 20.9.0
            node_major: 20
            variant: alpine
            dockerfile: ./alpine/node20/Dockerfile
          - ruby_version: 3.2
            node_version: 20.9.0
            node_major: 20
            variant: bookworm
            dockerfile: ./bookworm/node20/Dockerfile
          - ruby_version: 3.3
            node_version: 20.15.0
            node_major: 20
            variant: alpine
            dockerfile: ./alpine/node20/Dockerfile
          - ruby_version: 3.3
            node_version: 20.15.0
            node_major: 20
            variant: bookworm
            default: true
            dockerfile: ./bookworm/node20/Dockerfile
    name: Build image ${{ matrix.ruby_version }}-${{ matrix.node_major }}-${{ matrix.variant }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.variant }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.variant }}-
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            koen/ruby-node
          tags: |
            type=raw,value=${{ matrix.ruby_version }}-${{ matrix.node_major }},enable=${{ !!matrix.default }}
            type=raw,value=${{ matrix.ruby_version }}-${{ matrix.node_major }}-${{ matrix.variant }}
            type=raw,value=${{ matrix.tag }},enable=${{ !!matrix.tag }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            DISTRO=buster
            RUBY_VERSION=${{ matrix.ruby_version }}
            NODE_VERSION=${{ matrix.node_version }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
